### ISSUE TITLE
You need to exclude deconstruction planners

### ISSUE THREAD

**Issue by staviq** [NoxyNixie/Noxys_StackSizeMultiplier#1]
You need to exclude blueprints deconstruction planners and any selection tool.

If you let them stack, they lose their content when unstacked.

`local ignore = {
	["blueprint"] = true,
	["deconstruction-item"] = true,
	["selection-tool"] = true,
	["blueprint-book"] = true,
	["item-with-inventory"] = true,
	["armor"] = true,
}`

**Comment by NoxyNixie** [comment]
Ah thank you ;)
